//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabloDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characters
    {
        public Characters()
        {
            this.UsersGames = new HashSet<UsersGames>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> StatisticId { get; set; }
    
        public virtual Statistics Statistics { get; set; }
        public virtual ICollection<UsersGames> UsersGames { get; set; }
    }
}
