//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabloDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersGames
    {
        public UsersGames()
        {
            this.Items = new HashSet<Items>();
        }
    
        public int Id { get; set; }
        public int GameId { get; set; }
        public int UserId { get; set; }
        public int CharacterId { get; set; }
        public int Level { get; set; }
        public System.DateTime JoinedOn { get; set; }
        public decimal Cash { get; set; }
    
        public virtual Characters Characters { get; set; }
        public virtual Games Games { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Items> Items { get; set; }
    }
}
